### ISSUE TITLE
Who is Izy?

### ISSUE THREAD

**Issue by mylescc** [neefrehman/lzy#2]
This feels like a very sexist repo, like a repeat of the whole factory_girl gem disaster of 2017.

**Comment by neefrehman** [comment]
Hi @mylescc,

The script is called `lzy`, the first character is an 'L', which may look like an 'I' on the typeface used on github.com on MacOS, but in fact isn't.

Interesting bit of history: the script is called `lzy`, as it's the shortest way to represent something recognizable as 'lazy'. This is to represent `lzy.js` being a very small script compared to all other lazy-loaders.

Marking this issue as closed.
